# Generated by Django 3.2.9 on 2021-11-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='thumbnail',
        ),
    ]
